### PR TITLE
Update Event Types in creation and Fix Account Creation issues

### LINKED ISSUE #23: Add Event Types
Add DnD, Board Meeting, and Study group as event types.

### LINKED ISSUE #41: Creating an account with the same credentials as one in the database returns the user's object
The response from the database should instead be an error that the email is already associated with an account.

### LINKED ISSUE #42: Creating a user account shouldn't return the user's object on completion
Creating an account through the api currently returns a validated session token to the client. It should only return a success status or a fail status with messages where/if appropriate.

### PR DESCRIPTION
**Pull request by trevorlbrooks**
This pull resolves #23, resolves #41, and resolves #42. 
This pull also has the updates to add in metadata and has base for announcements.

### CODE REVIEW

File: acmPerms.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+GRANT SELECT, UPDATE, INSERT, DELETE ON acm.* TO 'acmuser'@'localhost';
```
Comment (HumbleHominid) [inline acmPerms.sql]: Don't think you meant to have this on here. Not sure though.

File: backend/model/login.php [hunk 2]
```diff
@@ -9,7 +9,7 @@
 define('ALGORITHM','HS512');
 
 class Login{
-
+  private $emailRegex = '/^[a-zA-Z]+[0-9]*@mtech\\.edu$/';
   private $domain = 'katie.mtech.edu/~acmuser';
```
Comment (HumbleHominid) [inline backend/model/login.php]: Gonna have to make a config for these eventually probably.

Comment (trevorlbrooks) [inline backend/model/login.php]: Currently have configs for backend as a phase two item. Will need to look through the frontend configs and do some thinking for that.
